### ISSUE TITLE
sleep after 1000 greenlet switches

### ISSUE THREAD

**Issue by e-max** [gevent-on-pypy/pypycore#1]
Hello 
I've found strange behavior of this gevent version.  Looks like it has some limits of  greenlet switches.

Consider this example.

``` python

LIMIT=1000
def  sleep():                                                                                                                                                                                   
    for i in xrange(LIMIT):                                                                                                                                                                     
        gevent.sleep(0)                                                                                                                                                                        


if __name__ == '__main__':                                                                                                                                                                     
    import time                                                                                                                                                                                
    start = time.time()                                                                                                                                                                        
    gevent.joinall([gevent.spawn(sleep)])                                                                                                                                                      
    print time.time() - start   
```

While LIMIT is less than 1000 this program works fast (~ 0.02 sec).

If we set LIMIT=1000 we will get huge slowdown to 60.02 sec.  ( and LIMIT=2000 give 120+ sec)

i've found some constant "count = 1000" in  "def _run_callbacks(self)"  but i don't understand why it should be here and what happens when this counter exceeds.

**Comment by schmir** [comment]
The code in question tries to give back control to the libev event loop.You would need to implement the outcommented code handling the self._timer0 timer in order to make this work like the cpython version.
Another workaround would be to not decrement the count variable. That way all the callbacks would have been handled...

Do you like to work on a fix? I don't have time to do it at the moment...sorry.

**Comment by arigo** [comment]
Can you apply the patch of not decrementing "count" in the current code (of course, with an XXX fix me better)?  It would have saved me the time of debugging why PyPy blocks in an example reported by a user :-)  Thanks!

**Comment by arigo** [comment]
Pull request #6

**Comment by lvella** [comment]
It is fixed now. Thanks!

**Comment by e-max** [comment]
Thanks Armin!
